/**
 * PDF invoice and packing-slip generators — black-only for thermal printers.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ApiRow } from "@/types";
import { formatCurrency } from "@/lib/constants";
import {
  BRAND_NAME,
  BRAND_STUDIO,
  BRAND_SHORT,
  BRAND_ADDRESS,
  BRAND_PHONE,
  BRAND_GSTIN,
  BRAND_EMAIL_HELLO,
  BRAND_WEBSITE,
} from "@/lib/brand";

interface InvoiceData {
  order: ApiRow;
  payment?: ApiRow | null;
}

const BLACK: [number, number, number] = [0, 0, 0];
const GRAY: [number, number, number] = [82, 82, 91];
const LIGHT: [number, number, number] = [228, 228, 231];

/** Draws shared company header on a jsPDF document (grayscale). */
function drawCompanyHeader(doc: jsPDF, title: string) {
  doc.setFillColor(...BLACK);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...BLACK);
  doc.text(BRAND_STUDIO, 14, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(BRAND_NAME, 14, 28);
  doc.text(BRAND_ADDRESS, 14, 33);
  doc.text(`${BRAND_PHONE}  ·  ${BRAND_EMAIL_HELLO}`, 14, 38);
  doc.text(BRAND_GSTIN, 14, 43);
  doc.text(BRAND_WEBSITE, 14, 48);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...BLACK);
  doc.text(title, doc.internal.pageSize.getWidth() - 14, 22, { align: "right" });

  doc.setDrawColor(...LIGHT);
  doc.setLineWidth(0.5);
  doc.line(14, 52, doc.internal.pageSize.getWidth() - 14, 52);
}

/** Draws shared footer border and thank-you line. */
function drawCompanyFooter(doc: jsPDF, pageH: number) {
  const w = doc.internal.pageSize.getWidth();
  doc.setDrawColor(...BLACK);
  doc.setLineWidth(0.6);
  doc.line(14, pageH - 22, w - 14, pageH - 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("Thank you for shopping with New Journey!", w / 2, pageH - 16, { align: "center" });
  doc.text(`${BRAND_STUDIO}  ·  ${BRAND_EMAIL_HELLO}  ·  ${BRAND_WEBSITE}`, w / 2, pageH - 11, { align: "center" });
  doc.text(`Generated by ${BRAND_SHORT} Studio OS`, w / 2, pageH - 6, { align: "center" });
}

function formatDate(iso?: string) {
  if (!iso) return "—";
  return iso.slice(0, 10);
}

function customerLines(order: ApiRow): string[] {
  const addr = (order.address || {}) as ApiRow;
  return [
    addr.full_name || order.user_email || "Customer",
    [addr.line1, addr.line2].filter(Boolean).join(", "),
    [addr.city, addr.state, addr.postal_code].filter(Boolean).join(", "),
    addr.phone || "",
    order.user_email || "",
  ].filter(Boolean);
}

/** Full A4 tax invoice PDF for a customer order. */
export function downloadFullInvoice({ order, payment }: InvoiceData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  drawCompanyHeader(doc, "TAX INVOICE");

  const orderNo = String(order.order_no || order.id);
  const rightX = doc.internal.pageSize.getWidth() - 14;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...BLACK);
  doc.text(`Invoice #: ${orderNo}`, rightX, 30, { align: "right" });
  doc.text(`Date: ${formatDate(order.created_at)}`, rightX, 35, { align: "right" });
  doc.text(`Order status: ${String(order.status || "—").replace(/_/g, " ")}`, rightX, 40, { align: "right" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Bill To", 14, 60);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  customerLines(order).forEach((line, i) => doc.text(line, 14, 66 + i * 5));

  const items = (order.items || []) as ApiRow[];
  autoTable(doc, {
    startY: 92,
    head: [["#", "Item", "Qty", "Unit price", "Amount"]],
    body: items.map((it, idx) => [
      String(idx + 1),
      String(it.name || "Product"),
      String(it.quantity ?? 1),
      formatCurrency(Number(it.price || 0)),
      formatCurrency(Number(it.price || 0) * Number(it.quantity || 1)),
    ]),
    theme: "grid",
    headStyles: { fillColor: BLACK, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: BLACK },
    columnStyles: { 0: { cellWidth: 10 }, 2: { halign: "center" }, 3: { halign: "right" }, 4: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });

  const finalY = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 120;
  let y = finalY + 8;

  const totals: [string, string][] = [
    ["Subtotal", formatCurrency(Number(order.subtotal || 0))],
    ["Discount", order.discount ? `−${formatCurrency(Number(order.discount))}` : "—"],
    ["Shipping", order.shipping ? formatCurrency(Number(order.shipping)) : "—"],
    ["GST", order.gst ? formatCurrency(Number(order.gst)) : "—"],
    ["Total", formatCurrency(Number(order.total || 0))],
  ];

  totals.forEach(([label, val]) => {
    doc.setFont("helvetica", label === "Total" ? "bold" : "normal");
    doc.text(label, rightX - 50, y, { align: "right" });
    doc.text(val, rightX, y, { align: "right" });
    y += 6;
  });

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Payment", 14, y);
  doc.setFont("helvetica", "normal");
  y += 5;
  doc.text(`Method: ${String(order.payment_method || payment?.method || "—").toUpperCase()}`, 14, y);
  y += 5;
  doc.text(`Status: ${String(payment?.status || "pending")}`, 14, y);
  if (payment?.transaction_id) {
    y += 5;
    doc.text(`Txn ID: ${payment.transaction_id}`, 14, y);
  }

  drawCompanyFooter(doc, doc.internal.pageSize.getHeight());
  doc.save(`Invoice-${orderNo}.pdf`);
}

/** Compact thermal-style packing slip (80×140mm, black ink only). */
export function downloadPackingSlip({ order, payment }: InvoiceData) {
  const doc = new jsPDF({ unit: "mm", format: [80, 140] });
  const w = doc.internal.pageSize.getWidth();
  const orderNo = String(order.order_no || order.id);
  const addr = (order.address || {}) as ApiRow;

  doc.setFillColor(...BLACK);
  doc.rect(0, 0, w, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(BRAND_SHORT, w / 2, 6.5, { align: "center" });

  doc.setTextColor(...BLACK);
  doc.setFontSize(8);
  doc.text(BRAND_STUDIO, w / 2, 15, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text(BRAND_GSTIN, w / 2, 19, { align: "center" });

  doc.setDrawColor(...LIGHT);
  doc.line(4, 21, w - 4, 21);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("PACKING SLIP", w / 2, 26, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text(`Order: ${orderNo}`, 4, 31);
  doc.text(`Date: ${formatDate(order.created_at)}`, 4, 35);
  doc.text(`Pay: ${String(payment?.status || "pending")}`, w - 4, 35, { align: "right" });

  doc.line(4, 37, w - 4, 37);
  doc.setFont("helvetica", "bold");
  doc.text("Ship To:", 4, 41);
  doc.setFont("helvetica", "normal");
  doc.text(String(addr.full_name || "Customer").slice(0, 28), 4, 45);
  doc.text(String(addr.line1 || addr.city || "").slice(0, 28), 4, 49);
  doc.text(String(addr.phone || "").slice(0, 28), 4, 53);

  doc.line(4, 55, w - 4, 55);
  doc.setFont("helvetica", "bold");
  doc.text("Items", 4, 59);

  const items = (order.items || []) as ApiRow[];
  let y = 63;
  doc.setFont("helvetica", "normal");
  items.forEach((it) => {
    doc.text(String(it.name || "Item").slice(0, 22), 4, y);
    doc.text(`x${Number(it.quantity || 1)}`, w - 4, y, { align: "right" });
    y += 4;
  });

  doc.line(4, y + 1, w - 4, y + 1);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("TOTAL", 4, y);
  doc.text(formatCurrency(Number(order.total || 0)), w - 4, y, { align: "right" });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6);
  doc.text("Thank you!", w / 2, y, { align: "center" });
  doc.text(BRAND_WEBSITE, w / 2, y + 4, { align: "center" });

  doc.setDrawColor(...BLACK);
  doc.setLineWidth(0.5);
  doc.line(4, 133, w - 4, 133);

  doc.save(`PackingSlip-${orderNo}.pdf`);
}
